version: 2
jobs:
  build:
    branches:
      only:
        - circleCi
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/my-project
    environment:
      PRIVACY_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/PRIVACY.md
      TERMS_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/TERMS.md

    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test
      - run: gradle build
      - run: cp build/bin/*.jar /tmp/artifacts

      # Save artifacts
      - store_artifacts:
        path: /tmp/artifacts
        destination: build
