version: 2.1
executors:
  my-test:
    docker:
      - image: circleci/mongo:4.0
jobs:
  build:
    docker:
      - image: java:8
    working_directory: ~/repo
    environment:
      PRIVACY_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/PRIVACY.md
      TERMS_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/TERMS.md

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-depen-{{ checksum "build.gradle" }}
            - v1-depen-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-depen-{{ checksum "build.gradle" }}
      - run:
          name: Create jar
          command: ./gradlew jar
      - run: mkdir -p workspace
      - run: cp build/bin/ffc-api.jar workspace/ffc-api.jar
      - persist_to_workspace:
          root: workspace
          paths:
            - ffc-api.jar
      - run: 'ls -al'
      - run: 'pwd'

  testrun:
    docker:
      - image: java:8
    executor: my-test
    working_directory: ~/repo
    environment:
      PRIVACY_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/PRIVACY.md
      TERMS_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/TERMS.md
      MONGODB_URI: mongodb://localhost:27017/data
      MONGODB_DBNAME: data
    steps:
      - attach_workspace:
          at: ~/repo/workspace
      - run:
          name: Print workspace
          command: find workspace
      - run:
          name: run ffc
          command: 'java -jar workspace/ffc-api.jar -port 23453 &'

workflows:
  version: 2
  flow:
    jobs:
      - build:
          filters:
            branches:
              only: circleCi
      - testrun:
          requires:
            - build
          filters:
            branches:
              only: circleCi
