version: 2
jobs:
  build:
    branches:
      only:
        - circleCi
    docker:
      - image: java:8
    working_directory: ~/repo
    environment:
      PRIVACY_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/PRIVACY.md
      TERMS_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/TERMS.md

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-depen-{{ checksum "build.gradle" }}
            - v1-depen-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-depen-{{ checksum "build.gradle" }}
      - run: ./gradlew jar
      - run: cp build/bin/*.jar /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts
          destination: build
