version: 2
jobs:
  build:
    branches:
      only:
        - circleCi
    docker:
      - image: java:8
    working_directory: ~/repo
    environment:
      PRIVACY_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/PRIVACY.md
      TERMS_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/TERMS.md

    steps:
      - checkout
      - run: gradle build
      - run: cp build/bin/*.jar /tmp/artifacts
