version: 2
jobs:
  build:
    branches:
      only:
        - circleCi
    docker:
      - image: java:8
    working_directory: ~/repo
    environment:
      PRIVACY_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/PRIVACY.md
      TERMS_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/TERMS.md

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-depen-{{ checksum "build.gradle" }}
            - v1-depen-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-depen-{{ checksum "build.gradle" }}
      - run:
          name: Create jar
          command: ./gradlew jar
      - run: 'ls -al'
      - run: 'pwd'

  testrun:
    branches:
      only:
        - circleCi
    docker:
      - image: java:8
        environment:
          PRIVACY_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/PRIVACY.md
          TERMS_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/TERMS.md
          MONGODB_URI: mongodb://localhost:27017/data
          MONGODB_DBNAME: data
      - image: circleci/mongo:4.0
    working_directory: ~/repo

    steps:
      - run:
          name: run ffc
          command: 'java -jar build/bin/ffc-api.jar &'
      - run:
          name: Sleep
          command: 'sleep 5'

workflows:
  version: 2
  buildtest:
    jobs:
      - build
      - testrun:
          requires:
            - build
