version: 2
jobs:
  build:
    branches:
      only:
        - circleCi
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      PRIVACY_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/PRIVACY.md
      TERMS_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/TERMS.md

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
