version: 2
jobs:
  build:
    branches:
      only:
        - circleCi
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mongo:4.0
      - image: circleci/node:11
    working_directory: ~/repo
    environment:
      PRIVACY_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/PRIVACY.md
      TERMS_URI: https://raw.githubusercontent.com/ffc-nectec/assets/master/legal/TERMS.md
      MONGODB_URI: mongodb://localhost:27017/data
      MONGODB_DBNAME: data

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-depen-{{ checksum "build.gradle" }}
            - v1-depen-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-depen-{{ checksum "build.gradle" }}
      - run:
          name: Create jar
          command: ./gradlew jar
      - run: cp build/bin/*.jar /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - run:
          name: clone test
          command: echo 'clone test'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          # https://learning.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman/
          name: Install postman
          command: npm install -g newman
      - run:
          name: start service
          command: |
            java -jar /tmp/artifacts/ffc-api.jar -port 8080 &
            sleep 5s
      - run:
          name: test postman
          command: |
            echo 'newman run mycollection.json'

